# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0002_song_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ImageField(blank=True, null=True, upload_to='album_art')),
                ('puplished', models.BooleanField(default=False)),
                ('Realease_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_art',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
        migrations.AddField(
            model_name='song',
            name='puplished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='album_songs', to='Hetro_app.Song'),
        ),
    ]
