# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0003_auto_20171118_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='album_name', max_length=50),
        ),
    ]
