# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0004_album_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='puplished',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='puplished',
            new_name='published',
        ),
    ]
