# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0005_auto_20170301_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.ManyToManyField(related_name='feature_songs', to='Hetro_app.Song')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='procuder',
            field=models.BooleanField(default=False),
        ),
    ]
