# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0006_auto_20171112_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='artist name', max_length=50)),
                ('albums', models.ManyToManyField(blank=True, related_name='artist_album', to='Hetro_app.Album')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to='Hetro_app.Profile')),
                ('songs', models.ManyToManyField(blank=True, related_name='artist_songs', to='Hetro_app.Song')),
            ],
        ),
    ]
