# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0007_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='artist_avatars'),
        ),
    ]
