# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0008_artist_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.CharField(blank=True, default='Artist Biography', max_length=500),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, default='Various', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, default='Various', max_length=50),
        ),
    ]
