# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0010_auto_20171118_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
