# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0010_auto_20171118_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Realease_date',
            new_name='release_date',
        ),
    ]
