# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hetro_app', '0012_auto_20180210_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
